export const types = {
    AUTH_START="AUTH_START",
    AUTH_SUCCESS="AUTH_SUCCESS",
    AUTH_FAILED="AUTH_FAILED",

    SIGN_OUT="SIGN_OUT",

    FETCH_USER_START="FETCH_USER_START",
    FETCH_USER_SUCCESS="FETCH_USER_SUCCESS",
    FETCH_USER_FAILED="FETCH_USER_FAILED",

    UPDATE_USER_START="UPDATE_USER_START",
    UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILED="UPDATE_USER_FAILED",


    CREATE_VENDOR_START="CREATE_VENDOR_START",
    CREATE_VENDOR_SUCCESS="CREATE_VENDOR_SUCCESS",
    CREATE_VENDOR_FAILED="CREATE_VENDOR_FAILED",

    
    UPDATE_VENDOR_START="UPDATE_VENDOR_START",
    UPDATE_VENDOR_SUCCESS="UPDATE_VENDOR_SUCCESS",
    UPDATE_VENDOR_FAILED="UPDATE_VENDOR_FAILED",

    SHOW_TOAST="SHOW_TOAST",
    HIDE_TOAST="HIDE_TOAST"
}
