export {default as Splash} from './splash'
export {default as Auth} from './auth'
export {default as Home} from './home'
export {default as CustomerProfile} from './profile/customerProfile'
export {default as BecomeAVendor} from './becomeAVendor'
export {default as Order} from './order'
export {default as Setting} from './setting'
export {default as Categories} from './categories/index'
export {default as VendorProfile} from './profile/vendorProfile'
export {default as Services} from './services'

